### PR TITLE
Add 4 Fiat Currency Into Mobile Wallet

### PR DESCRIPTION
**Pull request by ykris45**
Hey. I add 4 fiat currency in to mobile wallet
1. IDR = Indonesian Rupiahs
2. TRY = Turkish Lira
3. RUB = Russian Ruble
4. VND = Vietnamese Dong

its same as desktop wallet currency support
Thanks

### CODE REVIEW

**Comment by ykris45** [comment]
@nop33 could you review this bro

**Comment by nop33** [comment]
@ykris45 I will, but we have other priorities now, this one will have to wait.

**Comment by ykris45** [comment]
> @ykris45 I will, but we have other priorities now, this one will have to wait.

okay my beloved commanders of ALPH Rangers

**Comment by ykris45** [comment]
lets ran workflow again bro @nop33 i forget add ' to IDR section. I am on mobile right now

**Pull request merged**
