### PR TITLE
Metadata import from desktop wallet

### PR DESCRIPTION
**Pull request by nop33**
🎸 🤘 

@mvaivre you might need to delete all previous wallets with `deleteAllWallets()` in the `App.tsx` because I made changes in the wallets metadata structure.

### CODE REVIEW

**Comment by nop33** [comment]
I got a new dev build for Android, I'll upload it tmr: https://expo.dev/accounts/nop33/projects/mobile-wallet/builds/9b11d2b5-6374-42e5-b264-d12e19fee842

**Comment by nop33** [comment]
Rebased to fix conflicts

**Comment by mvaivre** [comment]
I can't make it work for now. Investigating.

image

**Comment by mvaivre** [comment]
On iOS, the scan screen overlaps the status bar:

image

**Review by mvaivre — APPROVED** [review]
I'm yet to try it on my actual device, but the implementation is super clean, congrats! 👏 
I'm approving anyway, we'll test a lot in the upcoming weeks.

**Comment by nop33** [comment]
I opened an issue for it: https://github.com/alephium/mobile-wallet/issues/176

**Pull request merged**
